# Generated by Django 3.2.4 on 2021-08-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_animal', models.CharField(max_length=20)),
                ('predador', models.CharField(max_length=20)),
                ('venenoso', models.CharField(max_length=20)),
                ('domestico', models.CharField(max_length=20)),
            ],
        ),
    ]
